dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  
addons:
  sonarcloud:
    organization: "allisondlucca-github"
    token: 
      secure: ${SONAR_TOKEN}

install:
  - pip install -r requirments.txt

script:
  - coverage run --omit=*test* -m unittest
  - coverage xml -i
  - sonar-scanner

after_success:
  - codecov
